spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_api_project_seed?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 5
      max-wait: 60000
